### ISSUE TITLE
Division by zero error

### ISSUE THREAD

**Issue by jnioche** [BaronStack/Rocksdb-Adviser#1]
The following command 

`python3 -m advisor.rule_parser_example --rules_spec=rules.ini --rocksdb_options=OPTIONS-000009 --log_files_path_prefix=LOG --stats_dump_period_sec=20`

gives

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/users/jnioche/.local/lib/python3.8/site-packages/advisor/rule_parser_example.py", line 89, in <module>
    main(args)
  File "/users/jnioche/.local/lib/python3.8/site-packages/advisor/rule_parser_example.py", line 41, in main
    triggered_rules = rule_spec_parser.get_triggered_rules(
  File "/users/jnioche/.local/lib/python3.8/site-packages/advisor/rule_parser.py", line 497, in get_triggered_rules
    self.trigger_conditions(data_sources)
  File "/users/jnioche/.local/lib/python3.8/site-packages/advisor/rule_parser.py", line 514, in trigger_conditions
    source.check_and_trigger_conditions(cond_subset)
  File "/users/jnioche/.local/lib/python3.8/site-packages/advisor/db_timeseries_parser.py", line 143, in check_and_trigger_conditions
    result = self.fetch_burst_epochs(
  File "/users/jnioche/.local/lib/python3.8/site-packages/advisor/db_timeseries_parser.py", line 82, in fetch_burst_epochs
    diff = diff * 100 / first_val
ZeroDivisionError: float division by zero
```

Strangely the same command ran fine a few moments before.

**Comment by shriram75** [comment]
I am having the same problem. Have you solved it?
